export const INITIAL_CATEGORIES = [
  { id: 'fruits', name: 'Fruits', slug: 'fruits', icon: 'Apple', active: true, order: 1 },
  { id: 'vegetables', name: 'Vegetables', slug: 'vegetables', icon: 'Carrot', active: true, order: 2 },
  { id: 'palakova', name: 'Palakova', slug: 'palakova', icon: 'Sparkles', active: true, order: 3 },
];

export const INITIAL_PRODUCTS = [
  {
    id: 'prod-palakova-01',
    name: 'Ashwath Fresh Palakova',
    description: 'Traditional authentic homemade milk sweet made with pure high-quality fresh milk and sugar. Rich, traditional taste directly from Tadakanapally.',
    category: 'Palakova',
    price: 130,
    unit: '250 grams',
    weight: '250g',
    imageUrl: 'https://images.unsplash.com/photo-1599785209707-a456fc1337cc?auto=format&fit=crop&q=80&w=600',
    stock: 50,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-apple-01',
    name: 'Fresh Shimla Apples',
    description: 'Crisp, juicy, and naturally sweet Shimla apples rich in fiber, vitamins, and anti-oxidants.',
    category: 'Fruits',
    price: 180,
    unit: 'Kg',
    weight: '1 Kg',
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&q=80&w=600',
    stock: 100,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-banana-01',
    name: 'Organic Robusta Bananas',
    description: 'Naturally ripened, nutrient-packed Robusta bananas ideal for healthy daily snacking.',
    category: 'Fruits',
    price: 60,
    unit: 'Dozen',
    weight: '12 Pcs',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&q=80&w=600',
    stock: 80,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-mango-01',
    name: 'Sweet Alphonso Mangoes',
    description: 'King of fruits! Premium quality farm-fresh Alphonso mangoes with rich aroma and rich sweet pulp.',
    category: 'Fruits',
    price: 120,
    unit: 'Kg',
    weight: '1 Kg',
    imageUrl: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=600',
    stock: 60,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-orange-01',
    name: 'Juicy Nagpur Oranges',
    description: 'Sun-ripened citrus oranges overflowing with natural Vitamin C and invigorating juice.',
    category: 'Fruits',
    price: 120,
    unit: 'Kg',
    weight: '1 Kg',
    imageUrl: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?auto=format&fit=crop&q=80&w=600',
    stock: 75,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-grapes-01',
    name: 'Seedless Black Grapes',
    description: 'Plump, sweet, and crisp black seedless grapes packed with antioxidants and health benefits.',
    category: 'Fruits',
    price: 90,
    unit: '500g',
    weight: '500 grams',
    imageUrl: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&q=80&w=600',
    stock: 45,
    featured: false,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-watermelon-01',
    name: 'Fresh Hybrid Watermelon',
    description: 'Hydrating, vibrant red, seedless watermelon harvested fresh from local fruit gardens.',
    category: 'Fruits',
    price: 50,
    unit: 'Piece',
    weight: 'Approx 2.5-3 Kg',
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=600',
    stock: 30,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-papaya-01',
    name: 'Organic Sweet Papaya',
    description: 'Digestive-friendly golden papaya with rich flavor and smooth texture.',
    category: 'Fruits',
    price: 60,
    unit: 'Kg',
    weight: '1 Kg',
    imageUrl: 'https://images.unsplash.com/photo-1517260739337-6799d239ce83?auto=format&fit=crop&q=80&w=600',
    stock: 40,
    featured: false,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-pomegranate-01',
    name: 'Royal Pomegranate (Anar)',
    description: 'Deep crimson ruby seeds bursting with fresh antioxidant juice.',
    category: 'Fruits',
    price: 190,
    unit: 'Kg',
    weight: '1 Kg',
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=600',
    stock: 55,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-pineapple-01',
    name: 'Sweet Hawaiian Pineapple',
    description: 'Aromatic, tangy-sweet tropical pineapple perfect for juices, salads, and fresh dessert.',
    category: 'Fruits',
    price: 70,
    unit: 'Piece',
    weight: '1 Piece',
    imageUrl: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&q=80&w=600',
    stock: 25,
    featured: false,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-guava-01',
    name: 'Fresh Country Guava',
    description: 'Crunchy green guava rich in vitamin C and dietary fibers.',
    category: 'Fruits',
    price: 80,
    unit: 'Kg',
    weight: '1 Kg',
    imageUrl: 'https://images.unsplash.com/photo-1536511135882-73a4369a475d?auto=format&fit=crop&q=80&w=600',
    stock: 50,
    featured: false,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-kiwi-01',
    name: 'Zespri Green Kiwi Pack',
    description: 'Exotic tangy green kiwis imported for high nutritional power and immunity.',
    category: 'Fruits',
    price: 120,
    unit: 'Pack',
    weight: '3 Pcs Pack',
    imageUrl: 'https://images.unsplash.com/photo-1585059819970-311922c2a0bf?auto=format&fit=crop&q=80&w=600',
    stock: 35,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-dragon-01',
    name: 'Exotic Red Dragon Fruit',
    description: 'Vibrant red-skinned pitaya with delicate sweet flavor and nutrient-rich seeds.',
    category: 'Fruits',
    price: 110,
    unit: 'Piece',
    weight: '1 Piece (350g+)',
    imageUrl: 'https://images.unsplash.com/photo-1527325678964-54921646bc9d?auto=format&fit=crop&q=80&w=600',
    stock: 20,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-combo-01',
    name: 'Daily Immunity Fruit Combo',
    description: 'Handpicked selection of 1kg Apples, 1 Dozen Bananas, 500g Grapes, and 2 Kiwis.',
    category: 'Fruits',
    price: 299,
    unit: 'Pack',
    weight: 'Approx 3.5 Kg',
    imageUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=600',
    stock: 15,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-juice-01',
    name: 'Cold Pressed Orange Juice (300ml)',
    description: '100% Pure, no added sugar or preservatives. Cold pressed from fresh Nagpur oranges.',
    category: 'Fruits',
    price: 90,
    unit: 'Pack',
    weight: '300 ml',
    imageUrl: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&q=80&w=600',
    stock: 40,
    featured: false,
    active: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-dryfruit-01',
    name: 'Premium California Almonds',
    description: 'Crunchy, rich, and high-protein raw California almonds.',
    category: 'Fruits',
    price: 240,
    unit: '250g',
    weight: '250 grams',
    imageUrl: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&q=80&w=600',
    stock: 50,
    featured: false,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-tomato-01',
    name: 'Farm Fresh Tomatoes',
    description: 'Ripe, juicy tomatoes picked fresh for curries, salads, and everyday cooking.',
    category: 'Vegetables',
    price: 40,
    unit: 'Kg',
    weight: '1 Kg',
    imageUrl: 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?auto=format&fit=crop&q=80&w=600',
    stock: 80,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-potato-01',
    name: 'Fresh Potatoes',
    description: 'Clean, firm potatoes ideal for daily home cooking.',
    category: 'Vegetables',
    price: 35,
    unit: 'Kg',
    weight: '1 Kg',
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=600',
    stock: 100,
    featured: false,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-carrot-01',
    name: 'Crunchy Red Carrots',
    description: 'Naturally sweet, crisp carrots for salads, juices, and curries.',
    category: 'Vegetables',
    price: 55,
    unit: 'Kg',
    weight: '1 Kg',
    imageUrl: 'https://images.unsplash.com/photo-1447175008436-054170c2e979?auto=format&fit=crop&q=80&w=600',
    stock: 60,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-spinach-01',
    name: 'Fresh Palak',
    description: 'Tender leafy spinach, washed and packed for easy cooking.',
    category: 'Vegetables',
    price: 30,
    unit: 'Bundle',
    weight: '1 Bundle',
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=600',
    stock: 45,
    featured: false,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const INITIAL_SETTINGS = {
  storeName: 'ASHWATH Fresh',
  businessTitle: 'Fresh Fruits & Grocery Delivery',
  phone: '9346763478',
  email: 'support@ashwathfresh.com',
  minimumOrder: 200,
  deliveryCharge: 0,
  freeDeliveryMinAmount: 300,
  paymentMethod: 'Cash on Delivery ONLY',
  codEnabled: true,
  address: {
    plot: '32',
    hNo: '7-2-32/P',
    roadNo: '5',
    area: 'Durga Nagar, Bairamalguda',
    city: 'Hyderabad',
    pincode: '500079',
    state: 'Telangana',
    originLocation: 'Tadakanapally, Kurnool',
    fullAddress: 'Plot: 32, H.No: 7-2-32/P, Road No: 5, Durga Nagar, Bairamalguda, Hyderabad - 500079'
  },
  logoUrl: '',
  bannerMessage: '⚡ Free Express Home Delivery on orders above ₹300! Minimum Order: ₹200 (COD Only).'
};

export const INITIAL_SAMPLE_ORDERS = [
  {
    id: 'ORD-1001',
    customerId: 'cust-demo-1',
    customerName: 'Ramesh Kumar',
    phone: '9848022334',
    email: 'ramesh@example.com',
    items: [
      { id: 'prod-apple-01', name: 'Fresh Shimla Apples', price: 180, unit: 'Kg', quantity: 1 },
      { id: 'prod-palakova-01', name: 'Ashwath Fresh Palakova', price: 130, unit: '250 grams', quantity: 1 }
    ],
    subtotal: 310,
    deliveryCharge: 0,
    totalAmount: 310,
    paymentMethod: 'COD',
    paymentStatus: 'Pending',
    orderStatus: 'Delivered',
    deliveryAddress: {
      fullName: 'Ramesh Kumar',
      phone: '9848022334',
      houseNo: 'Flat 402',
      street: 'Durga Nagar Main Rd',
      area: 'Bairamalguda',
      city: 'Hyderabad',
      pincode: '500079',
      notes: 'Please call before arriving'
    },
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString()
  },
  {
    id: 'ORD-1002',
    customerId: 'cust-demo-2',
    customerName: 'Srinivas Rao',
    phone: '9121445566',
    email: 'srinivas@example.com',
    items: [
      { id: 'prod-mango-01', name: 'Sweet Alphonso Mangoes', price: 120, unit: 'Kg', quantity: 2 },
      { id: 'prod-banana-01', name: 'Organic Robusta Bananas', price: 60, unit: 'Dozen', quantity: 1 }
    ],
    subtotal: 300,
    deliveryCharge: 0,
    totalAmount: 300,
    paymentMethod: 'COD',
    paymentStatus: 'Pending',
    orderStatus: 'Confirmed',
    deliveryAddress: {
      fullName: 'Srinivas Rao',
      phone: '9121445566',
      houseNo: 'H.No 12-4',
      street: 'Station Road',
      area: 'Tadakanapally',
      city: 'Kurnool',
      pincode: '518002',
      notes: 'Deliver in evening'
    },
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    updatedAt: new Date().toISOString()
  }
];
